"""Update Users

Revision ID: 16eed14eb37d
Revises: 8af845371a63
Create Date: 2024-10-30 00:18:18.333633

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "16eed14eb37d"
down_revision: Union[str, None] = "8af845371a63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
