"""Make UserORM.email unique field

Revision ID: 8edbe6fb8eb3
Revises: 16eed14eb37d
Create Date: 2024-10-30 00:27:50.997567

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8edbe6fb8eb3"
down_revision: Union[str, None] = "16eed14eb37d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
